### ISSUE TITLE
npm install node-mcp2210 fails at node-gyp rebuild

### ISSUE THREAD

**Issue by jamernmo** [Isolus/node-mcp2210#1]
On attempting to install node-mcp2210 I get a profusion of error messages ending with:
Failed at the node-mcp2210@1.0.2 install script 'node-gyp rebuild'.
I am running Lubuntu 16.04 LTS
Can you help please?  Debug logfile attached.

[npm-debug.log.txt](https://github.com/Isolus/node-mcp2210/files/877063/npm-debug.log.txt)

**Comment by Isolus** [comment]
I wrote this for an older version of nodejs. There seem to be some breaking changes in newer versions. I'll try to look into this in the next days.

**Comment by jamernmo** [comment]
Problem resolved some time ago.  Many thanks.
